on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          repository: matdavy1/docker-action-library
          ref: v14
          token: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}
          path: ./docker-action-library
      - name: run my action
        uses: ./docker-action-library/composite
        with:
          who-to-greet: 'Mat'
      