on: [push, workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello and goodbye
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          repository: enterprise-poc/docker-action-library
          ref: v16
          token: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}
          path: ./docker-action-library
      - name: run hello action
        with:
          who-to-greet: 'Mat'
      - name: run goodbye action
        uses: ./docker-action-library/goodbye/
        with:
          who-to-greet: 'Mat'